name: CI

on:
  push:
    branches:
      - main
jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: :installDist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login ghcr.io --username AMereBagatelle --password "$GITHUB_TOKEN"
      - name: Push Image
        run: |
          docker buildx build \
                  --tag  ghcr.io/amerebagatelle/t/bot:"$GITHUB_SHA" \
                  --tag  ghcr.io/amerebagatelle/t/bot:latest \
                  --file ./Dockerfile \
                  --output type=image,push=true .